nicolasvasilache/isl

- interface/test/CMakeLists.txt
- interface/test/gtest.cmake
A compatible version of gtest is downloaded and linked with the
interface tests when they are built.
> Bundle gtest with islpp interface test

- interface/isl.h.top
I want a C++ way of creating a context.
I think this factory method should belong here but I can also move it in my project.
> revert isl.h.top silly change, add a factory method

- include/isl/multi.h
Fixes the memory leak problem when using `mutli_*::get_dim_id` through C++ interface.
> multi.h: fix wrong memory management annotation

- isl_scheduler.c
Two slightly different fixes for the same problem (node points to invalid space
/ lookup in the right graph) were applied locally and upstream, both were
merged in and ended up undoing each other's work.
> fix automatic mis-merge

- interface/cpp.cc
The condition is already checked by the *_list_get_* function and
the use of ISLPP_ASSERT complicates the switch to the isl bindings
with exceptions (which do not have this macro).
> drop ISLPP_ASSERT call

- interface/cpp.cc
- interface/isl-noexceptions.h.pre
- interface/isl.h.pre
- interface/test/test_islpp.cc
They are not available in mainline isl and
the release() and get() methods can be used instead.
> drop generation of take() and keep() methods

- include/isl/schedule_node.h
This is needed for constructing an isl schedule tree from
another schedule tree representation.
> export isl_schedule_node_insert_mark

- doc/user.pod
- include/isl/schedule.h
- isl_schedule_constraints.h
Intersecting the domain can be usefully combined with
setting a prefix to obtain a partial schedule.
> export isl_schedule_constraints_intersect_domain

- include/isl/set.h
There is no unique way of constructing a set from a space.
> do no export isl_set_empty as a constructor

- interface/cpp.cc
- interface/isl-noexceptions.h
- interface/isl.h
End iterator uses -1 for position.  Begin iterator has been using 0 for
position, which could lead to begin() == end() not being a valid check
for list emptiness.  Use -1 as position of the begin iterator if the
list is empty.
> c++: ensure list.begin() == list.end() for empty lists

- doc/user.pod
- include/isl/schedule.h
- isl_options.c
- isl_options_private.h
- isl_scheduler.c
- test_inputs/schedule/noskew.sc
- test_inputs/schedule/noskew.st
- test_inputs/schedule/skew.sc
- test_inputs/schedule/skew.st
Some applications prefer schedules that do not perform
any skewing (or scaling).  Add an option that bounds
the sum of the absolute values of the coefficients to one
for each statement.
Like all other bounds on coefficients, this option
is ignored by the Feautrier scheduler.
It would be possible to introduce an option that bounds
this sum by an arbitrary number instead, but this would
not play very well with the incremental scheduler
as preventing the sum from accumulating beyond the bound
over successive cluster mergings would require introducing
extra variables in the ILP problem that encode
the absolute values of the coefficients of the original variables
(which may be linear combinations of the cluster variables).
In the special case of bound one, there is no such accumulation.
(Note …
> scheduler: optionally prevent skewing and scaling

- include/isl/ast_build.h
- isl_test_cpp-generic.cc
- isl_test_cpp-noexceptions.cc
- isl_test_cpp.cc
- isl_test_python.py
Unlike isl_ast_build_node_from_schedule_map (but like
all isl_ast_build_expr_from_* functions),
isl_ast_build_node_from_schedule is exported as an "overloaded"
function because the argument type uniquely determines
how it should be treated.  This is different from
isl_ast_build_node_from_schedule_map, first because
this function does not have a "union_map" suffix, but
more importantly, because the type itself does not
clarify that the argument is a schedule.
Signed-off-by: Sven Verdoolaege <sven.verdoolaege@gmail.com>
> export isl_ast_build_node_from_schedule

- doc/user.pod
- include/isl/ast.h
- isl_ast.c
- isl_ast_build.c
- isl_ast_build_expr.c
- isl_ast_build_private.h
- isl_ast_codegen.c
- isl_ast_private.h
- isl_convex_hull.c
- test_inputs/codegen/correlation.c
- test_inputs/codegen/gemm.c
In particular, if a generated for node corresponds
to a band member that is marked coincident, then also
mark this for node as coincident.
> isl_ast_build_node_from_schedule: propagate coincidence information

- doc/user.pod
- include/isl/list.h
- isl_list_templ.c
This will be used to reverse the members extracted from a band for mapping to threads.
> add isl_*_list_reverse

- include/isl/local_space.h
- include/isl/map.h
- include/isl/multi.h
- include/isl/set.h
- include/isl/space.h
isl_space_find_dim_by_name is left exported for now.
This export will be removed later.
> remove exports of most isl_*_find_dim_by_* functions

- include/isl/aff.h
- include/isl/constraint.h
- include/isl/local_space.h
- include/isl/map.h
- include/isl/multi.h
- include/isl/point.h
- include/isl/set.h
- include/isl/space.h
- include/isl/union_map.h
- include/isl/union_set.h
These functions were never meant to be exported.
There are still some exported functions left, but this
at least removes those that are not currently used
to prevent anyone from starting to use them.
> drop export of some functions with isl_dim_type argument

- doc/user.pod
- include/isl/aff.h
- isl_aff.c
These are needed for cleaning up MappedScop::findBestSync.
> fix some exports and add isl::multi_union_pw_aff::apply

- include/isl/multi.h
- include/isl/set.h
- include/isl/space.h
These functions were never meant to be exported.
There are still some exported functions left, but this
at least removes those that are not currently used
to prevent anyone from starting to use them.
> drop export of more functions with isl_dim_type argument

- doc/user.pod
- include/isl/space.h
- isl_space.c
This convenience function allows the user to check whether
a parameter is present in a space without having to call
isl_space_find_dim_by_id.  In particular, the user shouldn't
be forced to think of parameters as having a position.
Signed-off-by: Sven Verdoolaege <sven.verdoolaege@gmail.com>
> add isl_space_has_param_id

- cpp/cpp.h.pre
- cpp/isl-noexceptions.h.pre
This was missing from isl-0.18-1475-gf572a3d6 (export isl_ast_expr_op
as subclasses, Fri Mar 30 14:36:32 2018 +0200).
> drop enum class ast_op_type from C++ interface

- include/isl/map.h
This is necessary to make isl::map_list, exported before, compatible
with the C++ iterator template.
> isl_map_list: declare exported list functions

- include/isl/ilp.h
- isl_ilp.c
This reverts commit 9cc05132b009d6dba51d3fd596f04369d78f23ef.
The function isl_union_set_max_multi_union_pw_aff introduced by
that commit is not currently used by TC and a different variant
will be added to mainline isl, which would result in conflicts.
> Revert "create and export isl_union_set_max_multi_union_pw_aff"

- isl_test_cpp.cc
Combining the commits "introduce cpp bindings generation (with exceptions)"
and "keep track of domain in 0D isl_multi_pw_aff and isl_multi_union_pw_aff"
requires some adjustment of the expected error message.
This went unnoticed because the C++ bindings test do not get
run in this repository.
> fix miss merge

- doc/user.pod
- include/isl/space.h
- isl_space.c
The old names do not work out very well in the C++ bindings.
The new functions are also more generic and also support
creating a map space from a domain space.
> replace isl_space_{un}named_set_from_params by isl_space_add{un}named_tuple*

- cpp/cpp.h.pre
- cpp/isl-noexceptions.h.pre
- include/isl/schedule_node.h
- interface/cpp.cc
- interface/cpp.h
- interface/generator.cc
- interface/generator.h
- interface/python.cc
- interface/python.h
- isl_test_cpp-generic.cc
- isl_test_python.py
This may seem like a lot of code just to change a single line in TC,
but it does look nicer to be able to write
`bandNode.member_set_ast_loop_unroll(i);`
instead of
`bandNode.member_set_ast_loop_type(i, isl::ast_loop_type::unroll);`
In fact, it may even be a nicer interface for C as well, but it would require extra code,
while the C++ interface is automatically generated (admittedly using a lot more code,
but it can perhaps be reused in the future).
The new way of exporting this function is also (properly) supported in the Python bindings.
> change  export of isl_schedule_node_band_member_set_ast_loop_type 

- isl_scheduler.c
The introduction of merge callbacks in isl-0.18-816-g3d84f765 (Merge
heuristic callback (#6), Tue Jul 25 13:21:55 2017 +0200) broke
the handling of maximize coincidence in the absence of merge callbacks.
The commit it probably going to be reverted in the near future,
but in the mean time, the fix is needed to be able to merge master,
which introduces a new test case that breaks.
> fix merge callback fallout

- flags.sh
- include/isl/aff.h
- include/isl/ast_build.h
- include/isl/constraint.h
- include/isl/ilp.h
- include/isl/local_space.h
- include/isl/map.h
- include/isl/map_type.h
- include/isl/multi.h
- include/isl/point.h
- include/isl/schedule.h
- include/isl/schedule_node.h
- include/isl/set.h
- include/isl/space.h
- include/isl/union_map.h
- include/isl/union_set.h
This reduces the difference with mainline.
> drop stuff that is not currently used by TC
